package com.allinonefx.model;

import java.util.Date;

public class Address {

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column address.address_id
     *
     * @mbg.generated Sun Jan 28 10:11:43 CET 2018
     */
    private Short address_id;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column address.address
     *
     * @mbg.generated Sun Jan 28 10:11:43 CET 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column address.address2
     *
     * @mbg.generated Sun Jan 28 10:11:43 CET 2018
     */
    private String address2;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column address.district
     *
     * @mbg.generated Sun Jan 28 10:11:43 CET 2018
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column address.city_id
     *
     * @mbg.generated Sun Jan 28 10:11:43 CET 2018
     */
    private Short city_id;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column address.postal_code
     *
     * @mbg.generated Sun Jan 28 10:11:43 CET 2018
     */
    private String postal_code;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column address.phone
     *
     * @mbg.generated Sun Jan 28 10:11:43 CET 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column address.last_update
     *
     * @mbg.generated Sun Jan 28 10:11:43 CET 2018
     */
    private Date last_update;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column address.address_id
     *
     * @return the value of address.address_id
     *
     * @mbg.generated Sun Jan 28 10:11:43 CET 2018
     */
    public Short getAddress_id() {
        return address_id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column address.address_id
     *
     * @param address_id the value for address.address_id
     *
     * @mbg.generated Sun Jan 28 10:11:43 CET 2018
     */
    public void setAddress_id(Short address_id) {
        this.address_id = address_id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column address.address
     *
     * @return the value of address.address
     *
     * @mbg.generated Sun Jan 28 10:11:43 CET 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column address.address
     *
     * @param address the value for address.address
     *
     * @mbg.generated Sun Jan 28 10:11:43 CET 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column address.address2
     *
     * @return the value of address.address2
     *
     * @mbg.generated Sun Jan 28 10:11:43 CET 2018
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column address.address2
     *
     * @param address2 the value for address.address2
     *
     * @mbg.generated Sun Jan 28 10:11:43 CET 2018
     */
    public void setAddress2(String address2) {
        this.address2 = address2 == null ? null : address2.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column address.district
     *
     * @return the value of address.district
     *
     * @mbg.generated Sun Jan 28 10:11:43 CET 2018
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column address.district
     *
     * @param district the value for address.district
     *
     * @mbg.generated Sun Jan 28 10:11:43 CET 2018
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column address.city_id
     *
     * @return the value of address.city_id
     *
     * @mbg.generated Sun Jan 28 10:11:43 CET 2018
     */
    public Short getCity_id() {
        return city_id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column address.city_id
     *
     * @param city_id the value for address.city_id
     *
     * @mbg.generated Sun Jan 28 10:11:43 CET 2018
     */
    public void setCity_id(Short city_id) {
        this.city_id = city_id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column address.postal_code
     *
     * @return the value of address.postal_code
     *
     * @mbg.generated Sun Jan 28 10:11:43 CET 2018
     */
    public String getPostal_code() {
        return postal_code;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column address.postal_code
     *
     * @param postal_code the value for address.postal_code
     *
     * @mbg.generated Sun Jan 28 10:11:43 CET 2018
     */
    public void setPostal_code(String postal_code) {
        this.postal_code = postal_code == null ? null : postal_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column address.phone
     *
     * @return the value of address.phone
     *
     * @mbg.generated Sun Jan 28 10:11:43 CET 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column address.phone
     *
     * @param phone the value for address.phone
     *
     * @mbg.generated Sun Jan 28 10:11:43 CET 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column address.last_update
     *
     * @return the value of address.last_update
     *
     * @mbg.generated Sun Jan 28 10:11:43 CET 2018
     */
    public Date getLast_update() {
        return last_update;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column address.last_update
     *
     * @param last_update the value for address.last_update
     *
     * @mbg.generated Sun Jan 28 10:11:43 CET 2018
     */
    public void setLast_update(Date last_update) {
        this.last_update = last_update;
    }
}
