package com.allinonefx.model;

import com.jfoenix.controls.datamodels.treetable.RecursiveTreeObject;
import java.util.Date;

public class Category extends RecursiveTreeObject<Category> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_id
     *
     * @mbg.generated Fri Jan 19 14:15:35 CET 2018
     */
    private Byte category_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.name
     *
     * @mbg.generated Fri Jan 19 14:15:35 CET 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.last_update
     *
     * @mbg.generated Fri Jan 19 14:15:35 CET 2018
     */
    private Date last_update;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_id
     *
     * @return the value of category.category_id
     *
     * @mbg.generated Fri Jan 19 14:15:35 CET 2018
     */
    public Byte getCategory_id() {
        return category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_id
     *
     * @param category_id the value for category.category_id
     *
     * @mbg.generated Fri Jan 19 14:15:35 CET 2018
     */
    public void setCategory_id(Byte category_id) {
        this.category_id = category_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.name
     *
     * @return the value of category.name
     *
     * @mbg.generated Fri Jan 19 14:15:35 CET 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.name
     *
     * @param name the value for category.name
     *
     * @mbg.generated Fri Jan 19 14:15:35 CET 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.last_update
     *
     * @return the value of category.last_update
     *
     * @mbg.generated Fri Jan 19 14:15:35 CET 2018
     */
    public Date getLast_update() {
        return last_update;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.last_update
     *
     * @param last_update the value for category.last_update
     *
     * @mbg.generated Fri Jan 19 14:15:35 CET 2018
     */
    public void setLast_update(Date last_update) {
        this.last_update = last_update;
    }
}