package com.allinonefx.model;

import com.jfoenix.controls.datamodels.treetable.RecursiveTreeObject;
import java.util.Date;

public class Country extends RecursiveTreeObject<Country> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.country_id
     *
     * @mbg.generated Fri Jan 19 10:20:02 CET 2018
     */
    private Short country_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.country
     *
     * @mbg.generated Fri Jan 19 10:20:02 CET 2018
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.last_update
     *
     * @mbg.generated Fri Jan 19 10:20:02 CET 2018
     */
    private Date last_update;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.country_id
     *
     * @return the value of country.country_id
     *
     * @mbg.generated Fri Jan 19 10:20:02 CET 2018
     */
    public Short getCountry_id() {
        return country_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.country_id
     *
     * @param country_id the value for country.country_id
     *
     * @mbg.generated Fri Jan 19 10:20:02 CET 2018
     */
    public void setCountry_id(Short country_id) {
        this.country_id = country_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.country
     *
     * @return the value of country.country
     *
     * @mbg.generated Fri Jan 19 10:20:02 CET 2018
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.country
     *
     * @param country the value for country.country
     *
     * @mbg.generated Fri Jan 19 10:20:02 CET 2018
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.last_update
     *
     * @return the value of country.last_update
     *
     * @mbg.generated Fri Jan 19 10:20:02 CET 2018
     */
    public Date getLast_update() {
        return last_update;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.last_update
     *
     * @param last_update the value for country.last_update
     *
     * @mbg.generated Fri Jan 19 10:20:02 CET 2018
     */
    public void setLast_update(Date last_update) {
        this.last_update = last_update;
    }
}