package com.allinonefx.model;

import com.jfoenix.controls.datamodels.treetable.RecursiveTreeObject;
import java.util.Date;

public class Customer extends RecursiveTreeObject<Customer> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_id
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    private Short customer_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.store_id
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    private Byte store_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.first_name
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    private String first_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.last_name
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    private String last_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.email
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.address_id
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    private Short address_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.active
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    private Boolean active;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.create_date
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    private Date create_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.last_update
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    private Date last_update;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_id
     *
     * @return the value of customer.customer_id
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    public Short getCustomer_id() {
        return customer_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_id
     *
     * @param customer_id the value for customer.customer_id
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    public void setCustomer_id(Short customer_id) {
        this.customer_id = customer_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.store_id
     *
     * @return the value of customer.store_id
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    public Byte getStore_id() {
        return store_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.store_id
     *
     * @param store_id the value for customer.store_id
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    public void setStore_id(Byte store_id) {
        this.store_id = store_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.first_name
     *
     * @return the value of customer.first_name
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    public String getFirst_name() {
        return first_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.first_name
     *
     * @param first_name the value for customer.first_name
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    public void setFirst_name(String first_name) {
        this.first_name = first_name == null ? null : first_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.last_name
     *
     * @return the value of customer.last_name
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    public String getLast_name() {
        return last_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.last_name
     *
     * @param last_name the value for customer.last_name
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    public void setLast_name(String last_name) {
        this.last_name = last_name == null ? null : last_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.email
     *
     * @return the value of customer.email
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.email
     *
     * @param email the value for customer.email
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.address_id
     *
     * @return the value of customer.address_id
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    public Short getAddress_id() {
        return address_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.address_id
     *
     * @param address_id the value for customer.address_id
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    public void setAddress_id(Short address_id) {
        this.address_id = address_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.active
     *
     * @return the value of customer.active
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.active
     *
     * @param active the value for customer.active
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.create_date
     *
     * @return the value of customer.create_date
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.create_date
     *
     * @param create_date the value for customer.create_date
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.last_update
     *
     * @return the value of customer.last_update
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    public Date getLast_update() {
        return last_update;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.last_update
     *
     * @param last_update the value for customer.last_update
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    public void setLast_update(Date last_update) {
        this.last_update = last_update;
    }
}