package com.allinonefx.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class FilmExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public FilmExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andFilm_idIsNull() {
            addCriterion("film_id is null");
            return (Criteria) this;
        }

        public Criteria andFilm_idIsNotNull() {
            addCriterion("film_id is not null");
            return (Criteria) this;
        }

        public Criteria andFilm_idEqualTo(Short value) {
            addCriterion("film_id =", value, "film_id");
            return (Criteria) this;
        }

        public Criteria andFilm_idNotEqualTo(Short value) {
            addCriterion("film_id <>", value, "film_id");
            return (Criteria) this;
        }

        public Criteria andFilm_idGreaterThan(Short value) {
            addCriterion("film_id >", value, "film_id");
            return (Criteria) this;
        }

        public Criteria andFilm_idGreaterThanOrEqualTo(Short value) {
            addCriterion("film_id >=", value, "film_id");
            return (Criteria) this;
        }

        public Criteria andFilm_idLessThan(Short value) {
            addCriterion("film_id <", value, "film_id");
            return (Criteria) this;
        }

        public Criteria andFilm_idLessThanOrEqualTo(Short value) {
            addCriterion("film_id <=", value, "film_id");
            return (Criteria) this;
        }

        public Criteria andFilm_idIn(List<Short> values) {
            addCriterion("film_id in", values, "film_id");
            return (Criteria) this;
        }

        public Criteria andFilm_idNotIn(List<Short> values) {
            addCriterion("film_id not in", values, "film_id");
            return (Criteria) this;
        }

        public Criteria andFilm_idBetween(Short value1, Short value2) {
            addCriterion("film_id between", value1, value2, "film_id");
            return (Criteria) this;
        }

        public Criteria andFilm_idNotBetween(Short value1, Short value2) {
            addCriterion("film_id not between", value1, value2, "film_id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andRelease_yearIsNull() {
            addCriterion("release_year is null");
            return (Criteria) this;
        }

        public Criteria andRelease_yearIsNotNull() {
            addCriterion("release_year is not null");
            return (Criteria) this;
        }

        public Criteria andRelease_yearEqualTo(Date value) {
            addCriterionForJDBCDate("release_year =", value, "release_year");
            return (Criteria) this;
        }

        public Criteria andRelease_yearNotEqualTo(Date value) {
            addCriterionForJDBCDate("release_year <>", value, "release_year");
            return (Criteria) this;
        }

        public Criteria andRelease_yearGreaterThan(Date value) {
            addCriterionForJDBCDate("release_year >", value, "release_year");
            return (Criteria) this;
        }

        public Criteria andRelease_yearGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("release_year >=", value, "release_year");
            return (Criteria) this;
        }

        public Criteria andRelease_yearLessThan(Date value) {
            addCriterionForJDBCDate("release_year <", value, "release_year");
            return (Criteria) this;
        }

        public Criteria andRelease_yearLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("release_year <=", value, "release_year");
            return (Criteria) this;
        }

        public Criteria andRelease_yearIn(List<Date> values) {
            addCriterionForJDBCDate("release_year in", values, "release_year");
            return (Criteria) this;
        }

        public Criteria andRelease_yearNotIn(List<Date> values) {
            addCriterionForJDBCDate("release_year not in", values, "release_year");
            return (Criteria) this;
        }

        public Criteria andRelease_yearBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("release_year between", value1, value2, "release_year");
            return (Criteria) this;
        }

        public Criteria andRelease_yearNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("release_year not between", value1, value2, "release_year");
            return (Criteria) this;
        }

        public Criteria andLanguage_idIsNull() {
            addCriterion("language_id is null");
            return (Criteria) this;
        }

        public Criteria andLanguage_idIsNotNull() {
            addCriterion("language_id is not null");
            return (Criteria) this;
        }

        public Criteria andLanguage_idEqualTo(Byte value) {
            addCriterion("language_id =", value, "language_id");
            return (Criteria) this;
        }

        public Criteria andLanguage_idNotEqualTo(Byte value) {
            addCriterion("language_id <>", value, "language_id");
            return (Criteria) this;
        }

        public Criteria andLanguage_idGreaterThan(Byte value) {
            addCriterion("language_id >", value, "language_id");
            return (Criteria) this;
        }

        public Criteria andLanguage_idGreaterThanOrEqualTo(Byte value) {
            addCriterion("language_id >=", value, "language_id");
            return (Criteria) this;
        }

        public Criteria andLanguage_idLessThan(Byte value) {
            addCriterion("language_id <", value, "language_id");
            return (Criteria) this;
        }

        public Criteria andLanguage_idLessThanOrEqualTo(Byte value) {
            addCriterion("language_id <=", value, "language_id");
            return (Criteria) this;
        }

        public Criteria andLanguage_idIn(List<Byte> values) {
            addCriterion("language_id in", values, "language_id");
            return (Criteria) this;
        }

        public Criteria andLanguage_idNotIn(List<Byte> values) {
            addCriterion("language_id not in", values, "language_id");
            return (Criteria) this;
        }

        public Criteria andLanguage_idBetween(Byte value1, Byte value2) {
            addCriterion("language_id between", value1, value2, "language_id");
            return (Criteria) this;
        }

        public Criteria andLanguage_idNotBetween(Byte value1, Byte value2) {
            addCriterion("language_id not between", value1, value2, "language_id");
            return (Criteria) this;
        }

        public Criteria andOriginal_language_idIsNull() {
            addCriterion("original_language_id is null");
            return (Criteria) this;
        }

        public Criteria andOriginal_language_idIsNotNull() {
            addCriterion("original_language_id is not null");
            return (Criteria) this;
        }

        public Criteria andOriginal_language_idEqualTo(Byte value) {
            addCriterion("original_language_id =", value, "original_language_id");
            return (Criteria) this;
        }

        public Criteria andOriginal_language_idNotEqualTo(Byte value) {
            addCriterion("original_language_id <>", value, "original_language_id");
            return (Criteria) this;
        }

        public Criteria andOriginal_language_idGreaterThan(Byte value) {
            addCriterion("original_language_id >", value, "original_language_id");
            return (Criteria) this;
        }

        public Criteria andOriginal_language_idGreaterThanOrEqualTo(Byte value) {
            addCriterion("original_language_id >=", value, "original_language_id");
            return (Criteria) this;
        }

        public Criteria andOriginal_language_idLessThan(Byte value) {
            addCriterion("original_language_id <", value, "original_language_id");
            return (Criteria) this;
        }

        public Criteria andOriginal_language_idLessThanOrEqualTo(Byte value) {
            addCriterion("original_language_id <=", value, "original_language_id");
            return (Criteria) this;
        }

        public Criteria andOriginal_language_idIn(List<Byte> values) {
            addCriterion("original_language_id in", values, "original_language_id");
            return (Criteria) this;
        }

        public Criteria andOriginal_language_idNotIn(List<Byte> values) {
            addCriterion("original_language_id not in", values, "original_language_id");
            return (Criteria) this;
        }

        public Criteria andOriginal_language_idBetween(Byte value1, Byte value2) {
            addCriterion("original_language_id between", value1, value2, "original_language_id");
            return (Criteria) this;
        }

        public Criteria andOriginal_language_idNotBetween(Byte value1, Byte value2) {
            addCriterion("original_language_id not between", value1, value2, "original_language_id");
            return (Criteria) this;
        }

        public Criteria andRental_durationIsNull() {
            addCriterion("rental_duration is null");
            return (Criteria) this;
        }

        public Criteria andRental_durationIsNotNull() {
            addCriterion("rental_duration is not null");
            return (Criteria) this;
        }

        public Criteria andRental_durationEqualTo(Byte value) {
            addCriterion("rental_duration =", value, "rental_duration");
            return (Criteria) this;
        }

        public Criteria andRental_durationNotEqualTo(Byte value) {
            addCriterion("rental_duration <>", value, "rental_duration");
            return (Criteria) this;
        }

        public Criteria andRental_durationGreaterThan(Byte value) {
            addCriterion("rental_duration >", value, "rental_duration");
            return (Criteria) this;
        }

        public Criteria andRental_durationGreaterThanOrEqualTo(Byte value) {
            addCriterion("rental_duration >=", value, "rental_duration");
            return (Criteria) this;
        }

        public Criteria andRental_durationLessThan(Byte value) {
            addCriterion("rental_duration <", value, "rental_duration");
            return (Criteria) this;
        }

        public Criteria andRental_durationLessThanOrEqualTo(Byte value) {
            addCriterion("rental_duration <=", value, "rental_duration");
            return (Criteria) this;
        }

        public Criteria andRental_durationIn(List<Byte> values) {
            addCriterion("rental_duration in", values, "rental_duration");
            return (Criteria) this;
        }

        public Criteria andRental_durationNotIn(List<Byte> values) {
            addCriterion("rental_duration not in", values, "rental_duration");
            return (Criteria) this;
        }

        public Criteria andRental_durationBetween(Byte value1, Byte value2) {
            addCriterion("rental_duration between", value1, value2, "rental_duration");
            return (Criteria) this;
        }

        public Criteria andRental_durationNotBetween(Byte value1, Byte value2) {
            addCriterion("rental_duration not between", value1, value2, "rental_duration");
            return (Criteria) this;
        }

        public Criteria andRental_rateIsNull() {
            addCriterion("rental_rate is null");
            return (Criteria) this;
        }

        public Criteria andRental_rateIsNotNull() {
            addCriterion("rental_rate is not null");
            return (Criteria) this;
        }

        public Criteria andRental_rateEqualTo(BigDecimal value) {
            addCriterion("rental_rate =", value, "rental_rate");
            return (Criteria) this;
        }

        public Criteria andRental_rateNotEqualTo(BigDecimal value) {
            addCriterion("rental_rate <>", value, "rental_rate");
            return (Criteria) this;
        }

        public Criteria andRental_rateGreaterThan(BigDecimal value) {
            addCriterion("rental_rate >", value, "rental_rate");
            return (Criteria) this;
        }

        public Criteria andRental_rateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rental_rate >=", value, "rental_rate");
            return (Criteria) this;
        }

        public Criteria andRental_rateLessThan(BigDecimal value) {
            addCriterion("rental_rate <", value, "rental_rate");
            return (Criteria) this;
        }

        public Criteria andRental_rateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rental_rate <=", value, "rental_rate");
            return (Criteria) this;
        }

        public Criteria andRental_rateIn(List<BigDecimal> values) {
            addCriterion("rental_rate in", values, "rental_rate");
            return (Criteria) this;
        }

        public Criteria andRental_rateNotIn(List<BigDecimal> values) {
            addCriterion("rental_rate not in", values, "rental_rate");
            return (Criteria) this;
        }

        public Criteria andRental_rateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rental_rate between", value1, value2, "rental_rate");
            return (Criteria) this;
        }

        public Criteria andRental_rateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rental_rate not between", value1, value2, "rental_rate");
            return (Criteria) this;
        }

        public Criteria andLengthIsNull() {
            addCriterion("length is null");
            return (Criteria) this;
        }

        public Criteria andLengthIsNotNull() {
            addCriterion("length is not null");
            return (Criteria) this;
        }

        public Criteria andLengthEqualTo(Short value) {
            addCriterion("length =", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotEqualTo(Short value) {
            addCriterion("length <>", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthGreaterThan(Short value) {
            addCriterion("length >", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthGreaterThanOrEqualTo(Short value) {
            addCriterion("length >=", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthLessThan(Short value) {
            addCriterion("length <", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthLessThanOrEqualTo(Short value) {
            addCriterion("length <=", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthIn(List<Short> values) {
            addCriterion("length in", values, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotIn(List<Short> values) {
            addCriterion("length not in", values, "length");
            return (Criteria) this;
        }

        public Criteria andLengthBetween(Short value1, Short value2) {
            addCriterion("length between", value1, value2, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotBetween(Short value1, Short value2) {
            addCriterion("length not between", value1, value2, "length");
            return (Criteria) this;
        }

        public Criteria andReplacement_costIsNull() {
            addCriterion("replacement_cost is null");
            return (Criteria) this;
        }

        public Criteria andReplacement_costIsNotNull() {
            addCriterion("replacement_cost is not null");
            return (Criteria) this;
        }

        public Criteria andReplacement_costEqualTo(BigDecimal value) {
            addCriterion("replacement_cost =", value, "replacement_cost");
            return (Criteria) this;
        }

        public Criteria andReplacement_costNotEqualTo(BigDecimal value) {
            addCriterion("replacement_cost <>", value, "replacement_cost");
            return (Criteria) this;
        }

        public Criteria andReplacement_costGreaterThan(BigDecimal value) {
            addCriterion("replacement_cost >", value, "replacement_cost");
            return (Criteria) this;
        }

        public Criteria andReplacement_costGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("replacement_cost >=", value, "replacement_cost");
            return (Criteria) this;
        }

        public Criteria andReplacement_costLessThan(BigDecimal value) {
            addCriterion("replacement_cost <", value, "replacement_cost");
            return (Criteria) this;
        }

        public Criteria andReplacement_costLessThanOrEqualTo(BigDecimal value) {
            addCriterion("replacement_cost <=", value, "replacement_cost");
            return (Criteria) this;
        }

        public Criteria andReplacement_costIn(List<BigDecimal> values) {
            addCriterion("replacement_cost in", values, "replacement_cost");
            return (Criteria) this;
        }

        public Criteria andReplacement_costNotIn(List<BigDecimal> values) {
            addCriterion("replacement_cost not in", values, "replacement_cost");
            return (Criteria) this;
        }

        public Criteria andReplacement_costBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("replacement_cost between", value1, value2, "replacement_cost");
            return (Criteria) this;
        }

        public Criteria andReplacement_costNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("replacement_cost not between", value1, value2, "replacement_cost");
            return (Criteria) this;
        }

        public Criteria andRatingIsNull() {
            addCriterion("rating is null");
            return (Criteria) this;
        }

        public Criteria andRatingIsNotNull() {
            addCriterion("rating is not null");
            return (Criteria) this;
        }

        public Criteria andRatingEqualTo(String value) {
            addCriterion("rating =", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingNotEqualTo(String value) {
            addCriterion("rating <>", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingGreaterThan(String value) {
            addCriterion("rating >", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingGreaterThanOrEqualTo(String value) {
            addCriterion("rating >=", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingLessThan(String value) {
            addCriterion("rating <", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingLessThanOrEqualTo(String value) {
            addCriterion("rating <=", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingLike(String value) {
            addCriterion("rating like", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingNotLike(String value) {
            addCriterion("rating not like", value, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingIn(List<String> values) {
            addCriterion("rating in", values, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingNotIn(List<String> values) {
            addCriterion("rating not in", values, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingBetween(String value1, String value2) {
            addCriterion("rating between", value1, value2, "rating");
            return (Criteria) this;
        }

        public Criteria andRatingNotBetween(String value1, String value2) {
            addCriterion("rating not between", value1, value2, "rating");
            return (Criteria) this;
        }

        public Criteria andSpecial_featuresIsNull() {
            addCriterion("special_features is null");
            return (Criteria) this;
        }

        public Criteria andSpecial_featuresIsNotNull() {
            addCriterion("special_features is not null");
            return (Criteria) this;
        }

        public Criteria andSpecial_featuresEqualTo(String value) {
            addCriterion("special_features =", value, "special_features");
            return (Criteria) this;
        }

        public Criteria andSpecial_featuresNotEqualTo(String value) {
            addCriterion("special_features <>", value, "special_features");
            return (Criteria) this;
        }

        public Criteria andSpecial_featuresGreaterThan(String value) {
            addCriterion("special_features >", value, "special_features");
            return (Criteria) this;
        }

        public Criteria andSpecial_featuresGreaterThanOrEqualTo(String value) {
            addCriterion("special_features >=", value, "special_features");
            return (Criteria) this;
        }

        public Criteria andSpecial_featuresLessThan(String value) {
            addCriterion("special_features <", value, "special_features");
            return (Criteria) this;
        }

        public Criteria andSpecial_featuresLessThanOrEqualTo(String value) {
            addCriterion("special_features <=", value, "special_features");
            return (Criteria) this;
        }

        public Criteria andSpecial_featuresLike(String value) {
            addCriterion("special_features like", value, "special_features");
            return (Criteria) this;
        }

        public Criteria andSpecial_featuresNotLike(String value) {
            addCriterion("special_features not like", value, "special_features");
            return (Criteria) this;
        }

        public Criteria andSpecial_featuresIn(List<String> values) {
            addCriterion("special_features in", values, "special_features");
            return (Criteria) this;
        }

        public Criteria andSpecial_featuresNotIn(List<String> values) {
            addCriterion("special_features not in", values, "special_features");
            return (Criteria) this;
        }

        public Criteria andSpecial_featuresBetween(String value1, String value2) {
            addCriterion("special_features between", value1, value2, "special_features");
            return (Criteria) this;
        }

        public Criteria andSpecial_featuresNotBetween(String value1, String value2) {
            addCriterion("special_features not between", value1, value2, "special_features");
            return (Criteria) this;
        }

        public Criteria andLast_updateIsNull() {
            addCriterion("last_update is null");
            return (Criteria) this;
        }

        public Criteria andLast_updateIsNotNull() {
            addCriterion("last_update is not null");
            return (Criteria) this;
        }

        public Criteria andLast_updateEqualTo(Date value) {
            addCriterion("last_update =", value, "last_update");
            return (Criteria) this;
        }

        public Criteria andLast_updateNotEqualTo(Date value) {
            addCriterion("last_update <>", value, "last_update");
            return (Criteria) this;
        }

        public Criteria andLast_updateGreaterThan(Date value) {
            addCriterion("last_update >", value, "last_update");
            return (Criteria) this;
        }

        public Criteria andLast_updateGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update >=", value, "last_update");
            return (Criteria) this;
        }

        public Criteria andLast_updateLessThan(Date value) {
            addCriterion("last_update <", value, "last_update");
            return (Criteria) this;
        }

        public Criteria andLast_updateLessThanOrEqualTo(Date value) {
            addCriterion("last_update <=", value, "last_update");
            return (Criteria) this;
        }

        public Criteria andLast_updateIn(List<Date> values) {
            addCriterion("last_update in", values, "last_update");
            return (Criteria) this;
        }

        public Criteria andLast_updateNotIn(List<Date> values) {
            addCriterion("last_update not in", values, "last_update");
            return (Criteria) this;
        }

        public Criteria andLast_updateBetween(Date value1, Date value2) {
            addCriterion("last_update between", value1, value2, "last_update");
            return (Criteria) this;
        }

        public Criteria andLast_updateNotBetween(Date value1, Date value2) {
            addCriterion("last_update not between", value1, value2, "last_update");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table film
     *
     * @mbg.generated do_not_delete_during_merge Thu Jan 18 13:33:58 CET 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}