package com.allinonefx.model;

import com.jfoenix.controls.datamodels.treetable.RecursiveTreeObject;
import java.math.BigDecimal;
import java.util.Date;

public class Film extends RecursiveTreeObject<Film> {
        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column film.film_id
         *
         * @mbg.generated Thu Jan 18 13:33:58 CET 2018
         */
    private Short film_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.title
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.release_year
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    private Date release_year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.language_id
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    private Byte language_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.original_language_id
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    private Byte original_language_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.rental_duration
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    private Byte rental_duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.rental_rate
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    private BigDecimal rental_rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.length
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    private Short length;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.replacement_cost
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    private BigDecimal replacement_cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.rating
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    private String rating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.special_features
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    private String special_features;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.last_update
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    private Date last_update;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.description
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.film_id
     *
     * @return the value of film.film_id
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public Short getFilm_id() {
        return film_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.film_id
     *
     * @param film_id the value for film.film_id
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public void setFilm_id(Short film_id) {
        this.film_id = film_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.title
     *
     * @return the value of film.title
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.title
     *
     * @param title the value for film.title
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.release_year
     *
     * @return the value of film.release_year
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public Date getRelease_year() {
        return release_year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.release_year
     *
     * @param release_year the value for film.release_year
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public void setRelease_year(Date release_year) {
        this.release_year = release_year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.language_id
     *
     * @return the value of film.language_id
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public Byte getLanguage_id() {
        return language_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.language_id
     *
     * @param language_id the value for film.language_id
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public void setLanguage_id(Byte language_id) {
        this.language_id = language_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.original_language_id
     *
     * @return the value of film.original_language_id
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public Byte getOriginal_language_id() {
        return original_language_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.original_language_id
     *
     * @param original_language_id the value for film.original_language_id
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public void setOriginal_language_id(Byte original_language_id) {
        this.original_language_id = original_language_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.rental_duration
     *
     * @return the value of film.rental_duration
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public Byte getRental_duration() {
        return rental_duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.rental_duration
     *
     * @param rental_duration the value for film.rental_duration
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public void setRental_duration(Byte rental_duration) {
        this.rental_duration = rental_duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.rental_rate
     *
     * @return the value of film.rental_rate
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public BigDecimal getRental_rate() {
        return rental_rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.rental_rate
     *
     * @param rental_rate the value for film.rental_rate
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public void setRental_rate(BigDecimal rental_rate) {
        this.rental_rate = rental_rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.length
     *
     * @return the value of film.length
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public Short getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.length
     *
     * @param length the value for film.length
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public void setLength(Short length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.replacement_cost
     *
     * @return the value of film.replacement_cost
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public BigDecimal getReplacement_cost() {
        return replacement_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.replacement_cost
     *
     * @param replacement_cost the value for film.replacement_cost
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public void setReplacement_cost(BigDecimal replacement_cost) {
        this.replacement_cost = replacement_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.rating
     *
     * @return the value of film.rating
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public String getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.rating
     *
     * @param rating the value for film.rating
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public void setRating(String rating) {
        this.rating = rating == null ? null : rating.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.special_features
     *
     * @return the value of film.special_features
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public String getSpecial_features() {
        return special_features;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.special_features
     *
     * @param special_features the value for film.special_features
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public void setSpecial_features(String special_features) {
        this.special_features = special_features == null ? null : special_features.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.last_update
     *
     * @return the value of film.last_update
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public Date getLast_update() {
        return last_update;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.last_update
     *
     * @param last_update the value for film.last_update
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public void setLast_update(Date last_update) {
        this.last_update = last_update;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.description
     *
     * @return the value of film.description
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.description
     *
     * @param description the value for film.description
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}