package com.allinonefx.model;

import java.util.Date;

public class Staff {

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column staff.staff_id
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    private Byte staff_id;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column staff.first_name
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    private String first_name;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column staff.last_name
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    private String last_name;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column staff.address_id
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    private Short address_id;
    private Address address;
    private Address addressStore;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column staff.email
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column staff.store_id
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    private Byte store_id;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column staff.active
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    private Boolean active;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column staff.username
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column staff.password
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column staff.last_update
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    private Date last_update;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column staff.picture
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    private byte[] picture;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column staff.staff_id
     *
     * @return the value of staff.staff_id
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    public Byte getStaff_id() {
        return staff_id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column staff.staff_id
     *
     * @param staff_id the value for staff.staff_id
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    public void setStaff_id(Byte staff_id) {
        this.staff_id = staff_id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column staff.first_name
     *
     * @return the value of staff.first_name
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    public String getFirst_name() {
        return first_name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column staff.first_name
     *
     * @param first_name the value for staff.first_name
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    public void setFirst_name(String first_name) {
        this.first_name = first_name == null ? null : first_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column staff.last_name
     *
     * @return the value of staff.last_name
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    public String getLast_name() {
        return last_name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column staff.last_name
     *
     * @param last_name the value for staff.last_name
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    public void setLast_name(String last_name) {
        this.last_name = last_name == null ? null : last_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column staff.address_id
     *
     * @return the value of staff.address_id
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    public Short getAddress_id() {
        return address_id;
    }

    public Address getAddress() {
        return address;
    }

    public Address getAddressStore() {
        return addressStore;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column staff.address_id
     *
     * @param address_id the value for staff.address_id
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    public void setAddress_id(Short address_id) {
        this.address_id = address_id;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    public void setAddressStore(Address addressStore) {
        this.addressStore = addressStore;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column staff.email
     *
     * @return the value of staff.email
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column staff.email
     *
     * @param email the value for staff.email
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column staff.store_id
     *
     * @return the value of staff.store_id
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    public Byte getStore_id() {
        return store_id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column staff.store_id
     *
     * @param store_id the value for staff.store_id
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    public void setStore_id(Byte store_id) {
        this.store_id = store_id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column staff.active
     *
     * @return the value of staff.active
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column staff.active
     *
     * @param active the value for staff.active
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column staff.username
     *
     * @return the value of staff.username
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column staff.username
     *
     * @param username the value for staff.username
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column staff.password
     *
     * @return the value of staff.password
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column staff.password
     *
     * @param password the value for staff.password
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column staff.last_update
     *
     * @return the value of staff.last_update
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    public Date getLast_update() {
        return last_update;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column staff.last_update
     *
     * @param last_update the value for staff.last_update
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    public void setLast_update(Date last_update) {
        this.last_update = last_update;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column staff.picture
     *
     * @return the value of staff.picture
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    public byte[] getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column staff.picture
     *
     * @param picture the value for staff.picture
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    public void setPicture(byte[] picture) {
        this.picture = picture;
    }
}
