package com.allinonefx.model;

import java.util.Date;

public class Store {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.store_id
     *
     * @mbg.generated Sun Jan 28 18:14:29 CET 2018
     */
    private Byte store_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.manager_staff_id
     *
     * @mbg.generated Sun Jan 28 18:14:29 CET 2018
     */
    private Byte manager_staff_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.address_id
     *
     * @mbg.generated Sun Jan 28 18:14:29 CET 2018
     */
    private Short address_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.last_update
     *
     * @mbg.generated Sun Jan 28 18:14:29 CET 2018
     */
    private Date last_update;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.store_id
     *
     * @return the value of store.store_id
     *
     * @mbg.generated Sun Jan 28 18:14:29 CET 2018
     */
    public Byte getStore_id() {
        return store_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.store_id
     *
     * @param store_id the value for store.store_id
     *
     * @mbg.generated Sun Jan 28 18:14:29 CET 2018
     */
    public void setStore_id(Byte store_id) {
        this.store_id = store_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.manager_staff_id
     *
     * @return the value of store.manager_staff_id
     *
     * @mbg.generated Sun Jan 28 18:14:29 CET 2018
     */
    public Byte getManager_staff_id() {
        return manager_staff_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.manager_staff_id
     *
     * @param manager_staff_id the value for store.manager_staff_id
     *
     * @mbg.generated Sun Jan 28 18:14:29 CET 2018
     */
    public void setManager_staff_id(Byte manager_staff_id) {
        this.manager_staff_id = manager_staff_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.address_id
     *
     * @return the value of store.address_id
     *
     * @mbg.generated Sun Jan 28 18:14:29 CET 2018
     */
    public Short getAddress_id() {
        return address_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.address_id
     *
     * @param address_id the value for store.address_id
     *
     * @mbg.generated Sun Jan 28 18:14:29 CET 2018
     */
    public void setAddress_id(Short address_id) {
        this.address_id = address_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.last_update
     *
     * @return the value of store.last_update
     *
     * @mbg.generated Sun Jan 28 18:14:29 CET 2018
     */
    public Date getLast_update() {
        return last_update;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.last_update
     *
     * @param last_update the value for store.last_update
     *
     * @mbg.generated Sun Jan 28 18:14:29 CET 2018
     */
    public void setLast_update(Date last_update) {
        this.last_update = last_update;
    }
}