package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.Film;
import test.model.FilmExample;

public interface FilmMapper {
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    long countByExample(FilmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    int deleteByExample(FilmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    int deleteByPrimaryKey(Short film_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    int insert(Film record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    int insertSelective(Film record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    List<Film> selectByExampleWithBLOBs(FilmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    List<Film> selectByExample(FilmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    Film selectByPrimaryKey(Short film_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    int updateByExampleSelective(@Param("record") Film record, @Param("example") FilmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Film record, @Param("example") FilmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    int updateByExample(@Param("record") Film record, @Param("example") FilmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    int updateByPrimaryKeySelective(Film record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    int updateByPrimaryKeyWithBLOBs(Film record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated Thu Jan 18 13:33:58 CET 2018
     */
    int updateByPrimaryKey(Film record);
}