package com.allinonefx.dao;

import com.allinonefx.model.Customer;
import com.allinonefx.model.CustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table customer
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    long countByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table customer
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    int deleteByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table customer
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    int deleteByPrimaryKey(Short customer_id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table customer
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table customer
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table customer
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    List<Customer> selectByExample(CustomerExample example);

    List<Customer> selectByExampleWithAddress(Customer record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table customer
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    Customer selectByPrimaryKey(Short customer_id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table customer
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    int updateByExampleSelective(@Param("record") Customer record, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table customer
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    int updateByExample(@Param("record") Customer record, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table customer
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table customer
     *
     * @mbg.generated Fri Jan 19 09:32:55 CET 2018
     */
    int updateByPrimaryKey(Customer record);

}
