package com.allinonefx.dao;

import com.allinonefx.model.Language;
import com.allinonefx.model.LanguageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LanguageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbg.generated Sat Jan 27 19:28:17 CET 2018
     */
    long countByExample(LanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbg.generated Sat Jan 27 19:28:17 CET 2018
     */
    int deleteByExample(LanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbg.generated Sat Jan 27 19:28:17 CET 2018
     */
    int deleteByPrimaryKey(Byte language_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbg.generated Sat Jan 27 19:28:17 CET 2018
     */
    int insert(Language record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbg.generated Sat Jan 27 19:28:17 CET 2018
     */
    int insertSelective(Language record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbg.generated Sat Jan 27 19:28:17 CET 2018
     */
    List<Language> selectByExample(LanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbg.generated Sat Jan 27 19:28:17 CET 2018
     */
    Language selectByPrimaryKey(Byte language_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbg.generated Sat Jan 27 19:28:17 CET 2018
     */
    int updateByExampleSelective(@Param("record") Language record, @Param("example") LanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbg.generated Sat Jan 27 19:28:17 CET 2018
     */
    int updateByExample(@Param("record") Language record, @Param("example") LanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbg.generated Sat Jan 27 19:28:17 CET 2018
     */
    int updateByPrimaryKeySelective(Language record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbg.generated Sat Jan 27 19:28:17 CET 2018
     */
    int updateByPrimaryKey(Language record);
}