package com.allinonefx.dao;

import com.allinonefx.model.Staff;
import com.allinonefx.model.StaffExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StaffMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table staff
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    long countByExample(StaffExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table staff
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    int deleteByExample(StaffExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table staff
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    int deleteByPrimaryKey(Byte staff_id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table staff
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    int insert(Staff record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table staff
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    int insertSelective(Staff record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table staff
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    List<Staff> selectByExampleWithBLOBs(StaffExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table staff
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    List<Staff> selectByExample(StaffExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table staff
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    Staff selectByPrimaryKey(Byte staff_id);

    Staff selectByUsernameAndPassword(@Param("username") String username, @Param("password") String password);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table staff
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    int updateByExampleSelective(@Param("record") Staff record, @Param("example") StaffExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table staff
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Staff record, @Param("example") StaffExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table staff
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    int updateByExample(@Param("record") Staff record, @Param("example") StaffExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table staff
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    int updateByPrimaryKeySelective(Staff record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table staff
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    int updateByPrimaryKeyWithBLOBs(Staff record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table staff
     *
     * @mbg.generated Sun Jan 28 14:18:25 CET 2018
     */
    int updateByPrimaryKey(Staff record);
}
